### ISSUE TITLE
Help need got error "InitDB: database does not exist db.sqlite"

### ISSUE THREAD

**Issue by haroonabbasi** [haxpax/gosms#1]
Hi,

i am able to build dashboard.exe on windows but i get following error when i try to execute it.

```
2015/02/12 14:14:10 main:  Initializing gosms
2015/02/12 14:14:10 InitDB: database does not exist db.sqlite
2015/02/12 14:14:10 --- syncDB
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x1 addr=0x123083c4 pc=0x626db4]

runtime stack:
invalid spdelta 0x626d70 0x626db4 0xc4ee2 7015
runtime.gothrow(0x7afce8, 0x2a)
        c:/go/src/runtime/panic.go:503 +0x67
runtime.sigpanic()
        c:/go/src/runtime/os_windows.go:36 +0x53
invalid spdelta 0x626d70 0x626db4 0xc4ee2 7015
_cgo_ddefa58cbe9d_Cfunc__sqlite3_open_v2()
        ?:0 +0x44

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x626d70, 0x11c3da1c, 0x0)
        c:/go/src/runtime/cgocall.go:130 +0xbc fp=0x11c3da0c sp=0x11c3d9f4
github.com/mattn/go-sqlite3._Cfunc__sqlite3_open_v2(0xcf1708, 0x11c3da40, 0x10006, 0x0, 0x0)
        github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:104 +0x3f fp=0x11c3da1c sp=0x11c3da0c
github.com/mattn/go-sqlite3.(*SQLiteDriver).Open(0x11c18740, 0x75a768, 0x9, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/github.com/mattn/go-sqlite3/sqlite3.go:269 +0x1ac fp=0x11c3daf0 sp=0x11c3da1c
database/sql.(*DB).conn(0x11c1c9b0, 0x11c1231f, 0x0, 0x0)
        c:/go/src/database/sql/sql.go:664 +0x414 fp=0x11c3dba0 sp=0x11c3daf0
database/sql.(*DB).exec(0x11c1c9b0, 0x7eb348, 0x1d0, 0x11c3dcdc, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/database/sql/sql.go:884 +0x8a fp=0x11c3dc5c sp=0x11c3dba0
database/sql.(*DB).Exec(0x11c1c9b0, 0x7eb348, 0x1d0, 0x11c3dcdc, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/database/sql/sql.go:875 +0x9b fp=0x11c3dc9c sp=0x11c3dc5c
github.com/haxpax/gosms.syncDB(0x0, 0x0)
        C:/Go/src/github.com/haxpax/gosms/db.go:44 +0x13f fp=0x11c3dcf4 sp=0x11c3dc9c
github.com/haxpax/gosms.InitDB(0x74ea18, 0x7, 0x75a768, 0x9, 0x0, 0x0, 0x0)
        C:/Go/src/github.com/haxpax/gosms/db.go:23 +0x189 fp=0x11c3dd60 sp=0x11c3dcf4
main.main()
        C:/Go/src/github.com/haxpax/gosms/dashboard/main.go:21 +0x38e fp=0x11c3dfcc sp=0x11c3dd60
runtime.main()
        c:/go/src/runtime/proc.go:63 +0xcc fp=0x11c3dff0 sp=0x11c3dfcc
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1 fp=0x11c3dff4 sp=0x11c3dff0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1

goroutine 6 [chan receive]:
database/sql.(*DB).connectionOpener(0x11c1c9b0)
        c:/go/src/database/sql/sql.go:589 +0x43
created by database/sql.Open
        c:/go/src/database/sql/sql.go:452 +0x256
```

**Comment by Omie** [comment]
Hi

sorry, really busy day today, will take some time more but will get back soon.

What are you trying this on? Windows 7/8 32/64bit ? minigw setup went well ?

**Comment by Omie** [comment]
Hi

I have just tried building it on Windows from scratch on both 32,64 bit versions. Couldn't reproduce.
please make sure you have followed instructions correctly.
please also make sure its not a permissions issue, move the files to D:\ somewhere and check.

If still doesn't work, please get back with exact steps that you performed when you got this error along with platform related information.

Thanks
